//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsVn.Web {
    
    
    public partial class Category {
        
        /// <summary>
        /// pletHotNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.SpecialPostsPortlet pletHotNews;
        
        /// <summary>
        /// pletLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.LatestPostsPortlet pletLatestNews;
        
        /// <summary>
        /// pletCatePostList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.CategorizedPostList pletCatePostList;
        
        /// <summary>
        /// QuickSearchBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.QuickSearchBox QuickSearchBox1;
        
        /// <summary>
        /// pletFocusPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.FocusPostsPortlet pletFocusPost;
        
        /// <summary>
        /// adboxArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl adboxArea;
        
        /// <summary>
        /// HotVideoList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.HotVideoList HotVideoList1;
    }
}
