//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsVn.Web {
    
    
    public partial class Default {
        
        /// <summary>
        /// pletHotNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.SpecialPostsPortlet pletHotNews;
        
        /// <summary>
        /// pletLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.LatestPostsPortlet pletLatestNews;
        
        /// <summary>
        /// pletSpecialEvents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.SpecialEventsPortlet pletSpecialEvents;
        
        /// <summary>
        /// postArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl postArea;
        
        /// <summary>
        /// AdBoxList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.AdBoxList AdBoxList1;
        
        /// <summary>
        /// pletSideTabBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.SideTabsBox pletSideTabBar;
        
        /// <summary>
        /// HotVideoList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NewsVn.Web.Modules.HotVideoList HotVideoList1;
    }
}
